### ISSUE TITLE
ValueError: only one element tensors can be converted to Python scalars

### ISSUE THREAD

**Issue by mikeyEcology** [zhen-he/tracking-by-animation#17]
Hi, 
I tried running the code to train and I got this error:

> (track) PS C:\Users\...\trained_models\tracking-by-animation> python run.py --task sprite
Task: sprite
Experiment: tba
Configuration:  ['act']
Model: default
Total batch size: 64, GPU number: 2, GPU batch size: 32
Parameter number: 1.018 M
tensor([[0.0649, 0.0000, 0.0000, 0.0000]], device='cuda:0')
C:\Users\...\Miniconda3\envs\track\lib\site-packages\torch\nn\parallel\_functions.py:61: UserWarning: Was asked to ga
ther along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "run.py", line 265, in <module>
    run_train_epoch(batch_id_start)
  File "run.py", line 227, in run_train_epoch
    loss = run_batch(batch_id, 'train')
  File "run.py", line 189, in run_batch
    loss, forward_time = forward(X_seq, **kwargs)
  File "run.py", line 165, in forward
    loss = net(X_seq, **kwargs)
  File "C:\Users\...\Miniconda3\envs\track\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\...\trained_models\tracking-by-animation\modules\net.py", line 78, in forward
    loss = self.loss_calculator(X_r_seq, X_seq, area, **ka)
  File "C:\Users\...\Miniconda3\envs\track\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\...\trained_models\tracking-by-animation\modules\loss_calculator.py", line 36, in forward
    losses['tight'] = loss_tight.item()
ValueError: only one element tensors can be converted to Python scalars

Below I pasted my environment information. Do you have any recommendations?
Thank you,
Mikey

Environment information:

> Name                    Version                   Build  Channel
backcall                  0.2.0                      py_0
blas                      1.0                         mkl
ca-certificates           2020.7.22                     0
certifi                   2020.6.20                py37_0
cffi                      1.14.2           py37h7a1dbc1_0
colorama                  0.4.3                      py_0
cudatoolkit               10.1.243             h74a9793_0
cycler                    0.10.0                   py37_0
decorator                 4.4.2                      py_0
freetype                  2.10.2               hd328e21_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
intel-openmp              2020.2                      254
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.17.0           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
jedi                      0.17.2                   py37_0
jpeg                      9b                   hb83a4c4_2
jupyter_client            6.1.6                      py_0
jupyter_core              4.6.3                    py37_0
kiwisolver                1.2.0            py37h74a9793_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libtiff                   4.1.0                h56a325e_1
lz4-c                     1.9.2                h62dcd97_1
matplotlib                3.3.1                         0
matplotlib-base           3.3.1            py37hba9282a_0
mkl                       2020.2                      256
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.1.0            py37h45dec08_0
mkl_random                1.1.1            py37h47e9c7a_0
ninja                     1.10.0           py37h7ef1ec2_0
numpy                     1.19.1           py37h5510c5b_0
numpy-base                1.19.1           py37ha3acd2a_0
olefile                   0.46                     py37_0
opencv-python             4.4.0.42                 pypi_0    pypi
openssl                   1.1.1g               he774522_1
parso                     0.7.0                      py_0
pickleshare               0.7.5                 py37_1001
pillow                    7.2.0            py37hcc1f983_0
pip                       20.2.2                   py37_0
prompt-toolkit            3.0.5                      py_0
pycparser                 2.20                       py_2
pygments                  2.6.1                      py_0
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h6538335_2
python                    3.7.7                h81c818b_4
python-dateutil           2.8.1                      py_0
pytorch                   1.4.0           py3.7_cuda101_cudnn7_0    pytorch
pywin32                   227              py37he774522_1
pyzmq                     19.0.1           py37ha925a31_1
qt                        5.9.7            vc14h73c81de_0
scipy                     1.5.2            py37h9439919_0
setuptools                49.6.0                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.15.0                     py_0
sqlite                    3.33.0               h2a8f88b_0
tk                        8.6.10               he774522_0
torchvision               0.5.0                py37_cu101    pytorch
tornado                   6.0.4            py37he774522_1
traitlets                 4.3.3                    py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wcwidth                   0.2.5                      py_0
wheel                     0.35.1                     py_0
wincertstore              0.2                      py37_0
xz                        5.2.5                h62dcd97_0
zeromq                    4.3.2                ha925a31_2
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.5                h04227a9_0

Edit: I get the same error when I run `python run.py --task mnist` instead of `python run.py --task sprite`

**Comment by zhen-he** [comment]
Hi, could you please try the following:
1. Modify Line 27 of `modules/renderer.py` as `area = area.view(-1, o.T, o.O, 1).mean(2)  # N * T * 1`;
2. Modify Line 34 of `modules/loss_calculator.py` as `loss_tight = lam_t * area.sum()`;
3. Run the code and check whether there are warnings/errors.

Best,
Zhen

**Comment by mikeyEcology** [comment]
Thank you for your response @zhen-he. I made these changes and it ran for quite a while. I got this output

> Total batch size: 64, GPU number: 2, GPU batch size: 32
Parameter number: 1.018 M
tensor([[0.1042, 0.0000, 0.0000, 0.0000]], device='cuda:0'
recon: 0.978, tight: 0.015, entr: 0.000, loss_app: 0.007

Suggesting it's working. But then I got this, which makes sense because I'm using my gpus in another project. 
> RuntimeError: CUDA error: out of memory

I'll try running again when I free up some gpu time.
