### ISSUE TITLE
`AttributeError: module 'modules.submodules' has no attribute 'MMDLoss'` while running `python run.py --task mnist`

### ISSUE THREAD

**Issue by linkinpark213** [zhen-he/tracking-by-animation#2]
I ran `python run.py --task mnist` and met with this issue. Here is the full output.
```
(torch03py36) ➜  /home/xxx/Source/tracking-by-animation git:(master) ✗ python run.py --task mnist
Task: mnist
Experiment: tba
Configuration:  ['act']
Model: default
Total batch size: 64, GPU number: 2, GPU batch size: 32
Traceback (most recent call last):
  File "run.py", line 127, in <module>
    net = Net(o).cuda()
  File "/home/linkinpark213/Source/tracking-by-animation/modules/net.py", line 28, in __init__
    self.loss_calculator = nn.DataParallel(LossCalculator(o), device_ids)
  File "/home/linkinpark213/Source/tracking-by-animation/modules/loss_calculator.py", line 17, in __init__
    self.mmd = smd.MMDLoss(sigmas=[0.01, 0.03, 0.1, 0.3, 1, 3])
AttributeError: module 'modules.submodules' has no attribute 'MMDLoss'
```
By the way, I can't seem to find any `MMDLoss` in the project, either. Is there any file missing?

**Comment by zhen-he** [comment]
Corrected. It was used previously and please just remove it.

Thanks for reporting.
