### ISSUE TITLE
RuntimeError: cuda runtime error (2): out of memory when running `python run.py`

### ISSUE THREAD

**Issue by linkinpark213** [zhen-he/tracking-by-animation#3]
When I run `python run.py`(the `--task` parameter is `mnist` or `sprite`), I'll get `RuntimeError`s. Here is the full output of `python run.py --task sprite`.
```
(torch03py36) ➜  /home/xxx/Source/tracking-by-animation git:(master) ✗ python run.py --task sprite
Task: sprite
Experiment: tba
Configuration:  ['act']
Model: default
Total batch size: 64, GPU number: 1, GPU batch size: 64
Parameter number: 1.018 M
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1523244252089/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "run.py", line 262, in <module>
    run_train_epoch(batch_id_start)
  File "run.py", line 224, in run_train_epoch
    loss = run_batch(batch_id, 'train')
  File "run.py", line 190, in run_batch
    loss, forward_time = forward(X_seq, **kwargs)
  File "run.py", line 167, in forward
    loss = net(X_seq, **kwargs)
  File "/home/linkinpark213/anaconda3/envs/torch03py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/linkinpark213/Source/tracking-by-animation/modules/net.py", line 55, in forward
    C_o_seq = self.feature_extractor(X_seq_cat) # N * T * M * R
  File "/home/linkinpark213/anaconda3/envs/torch03py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/linkinpark213/anaconda3/envs/torch03py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 71, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/linkinpark213/anaconda3/envs/torch03py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/linkinpark213/Source/tracking-by-animation/modules/feature_extractor.py", line 21, in forward
    C3_seq = self.cnn(X_seq)                                             # NT * C3_3 * C3_1 * C3_2
  File "/home/linkinpark213/anaconda3/envs/torch03py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/linkinpark213/Source/tracking-by-animation/modules/submodules.py", line 182, in forward
    H = getattr(self, 'conv'+str(i))(H)
  File "/home/linkinpark213/anaconda3/envs/torch03py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/linkinpark213/anaconda3/envs/torch03py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/linkinpark213/anaconda3/envs/torch03py36/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1523244252089/work/torch/lib/THC/generic/THCStorage.cu:58
```
And my environment is:
- Intel(R) Core(TM) i7-4790
- NVIDIA GeForce GTX 1080Ti
- 16GB RAM
- Ubuntu 18.04 (Kernel: 4.15.0-48-generic)
- CUDA 8.0 / 10.0
- Python 3.6.8
- PyTorch 0.3.1

Is it insufficient for running the training code of TBA? Thanks in advance.

**Comment by zhen-he** [comment]
I guess you need at least two 1080Ti GPUs (you can try the command `watch -n 0.3 nvidia-smi` to monitor the used GPU memory). Alternatively, you can reduce the training batch size.

**Comment by linkinpark213** [comment]
Thanks. I tried to run it with 4 GTX1080Ti GPUs in parallel but it seems that only GPU 0 is working. Could I enable multi-GPU training?

**Comment by zhen-he** [comment]
Yeah please try `torch.cuda.device_count()` to check your available GPU number (see line 120 in `run.py`).

**Comment by linkinpark213** [comment]
Thank you. I have successfully run the training code with 4 GPUs.
